name: "golangci-lint"

on:
  # push:
  #   branches:
  #     - '**'

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  GO_VERSION: 1.20.2

jobs:
  codeql:
    name: golangci-lint Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest