---
name: "Gosec"
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  GO_VERSION: 1.20

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GOROOT: $(go env GOROOT)
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go Version
        run: go version

      - name: Go Envirioment Variables
        run: go env

      # - name: Run Gosec Security Scanner
      #   uses: securego/gosec@master
      #   with:
      #     args: ./...

      - name: Run Gosec Security Scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -conf .gosec.json ./...
